name: RentNest Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: authToken
    value: ''
  - key: userId
    value: ''
  - key: propertyId
    value: ''
  - key: categoryId
    value: ''
  - key: rentalRequestId
    value: ''
  - key: paymentId
    value: ''
  - key: reviewId
    value: ''
  - key: sslStorePassword
    value: ''
  - key: transactionId
    value: ''
  - key: gatewayPageUrl
    value: ''
  - key: gatewayStatus
    value: ''
  - key: verifyKey
    value: ''
  - key: verifySign
    value: ''
  - key: transactionId1
    value: ''
  - key: transactionId2
    value: ''
